# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: monitoring-daemon
# spec:
#   selector:
#     matchlabels:
#       app: monitoring-agent
#     template:
#       metadata:
#         labels:
#           app: monitoring-agent
#       spec:
#         containers:
#         - name: monitoring-agent
#           image: monitoring-agent

Name: elasticsearch
Namespace: kube-system
Image: k8s.gcr.io/fluentd-elasticsearch:1.20

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
spec:
  selector:
    matchlabels:
      app: elasticsearch
    template:
      metadata:
        labels:
          app: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          image: k8s.gcr.io/fluentd-elasticsearch:1.20