# apiVersion: apps/v1
# kind: Deployment

# metadata:
#   name: myapp-ReplicaSet
#   labels:
#     app: myapp
#     type: front-end

# spec:  
#   template:
    
#     metadata:
#       name: myapp-Pod
#       labels:
#         app: myapp
#         type: front-end
    
#     spec:
#       containers:
#         - name: nginx-container
#           image: nginx
#           resource:
  
#   replicas: 3
#   selector:
#     matchLabels:
#       type: front-end





# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: blue
# spec:
#   replicas: 6
#   selector:
#     matchLabels:
#       run: nginx
#   template:
#     metadata:
#       labels:
#         run: nginx
#     spec:
#       containers:
#       - image: nginx
#         imagePullPolicy: Always
#         name: nginx
#         resources:

#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: color
#                 operator: In
#                 values:
#                 - blue
# ##runs on nodes with color=blue label


apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            ## runs on master node